### ISSUE TITLE
Array quoting

### ISSUE THREAD

**Issue by esatterwhite** [crysalead-js/sql-dialect#10]
It looks like the array conversion is incorrect. Is correctly wrapping it in braces, but It needs to be a single quoted string

#### Incorrect
```sql
{test}
```
vs

#### Correct
```sql
'{test}'
```

**Comment by jails** [comment]
Good catch :+1:, fixed in https://github.com/crysalead-js/sql-dialect/commit/2340cce851a84652e286a97374965d0b6965467f
