### ISSUE TITLE
Invalid operators (not) exists

### ISSUE THREAD

**Issue by esatterwhite** [crysalead-js/sql-dialect#11]
The default operators have exists + not exists as list. 
```javascript
':exists'      : { builder: 'list' },
':not exists'  : { builder: 'list' },
```

I'm fairly certain `exists` takes a sub query in all cases

```sql
SELECT *
FROM table_a
WHERE table_a.column = X
AND EXISTS (
  SELECT 1
  FROM table_b where table_b.a = table_a.id
)
```

Even setting them to an empty builder / undefined builder causes the to render incorrectly

```javascript
':exists' :  { },
':not exists'  :  undefined,
```
I have to  delete them from the default operators, and express the key in my query as `:exists()`  for it to work correctly.

The operator selection logic doesn't let me fully override them, I should be able to specify `null` or `undefined` and get the default behavior. But It doesn't seem like I can do that.

**Comment by jails** [comment]
They need to be removed from default operators ?

**Comment by esatterwhite** [comment]
Yes, I believe so. I'm not sure if that breaks anything else though.

I had to copy them out of the package, and manually remove them.

**Comment by jails** [comment]
Willing to create the PR ?
